#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_ENV_FILE="${ROOT_ENV_FILE:-$SCRIPT_DIR/../.env}"
OUT_ENV_FILE="${OUT_ENV_FILE:-$SCRIPT_DIR/.env}"

if ! command -v security >/dev/null 2>&1; then
  echo "Error: macOS security command is required." >&2
  exit 1
fi

if [[ ! -f "$ROOT_ENV_FILE" ]]; then
  echo "Error: root env file not found: $ROOT_ENV_FILE" >&2
  echo "Run ./scripts/setup-hyperapi-token.sh from the project root first." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ROOT_ENV_FILE"
set +a

BASE_URL="${HYPERAPI_BASE_URL:-https://hyperapi.cc}"
USER_ID="${HYPERAPI_USER_ID:-}"
KEYCHAIN_SERVICE="${HYPERAPI_KEYCHAIN_SERVICE:-newapi-account-scraper.hyperapi}"

if [[ -z "$USER_ID" ]]; then
  echo "Error: HYPERAPI_USER_ID is missing in $ROOT_ENV_FILE." >&2
  echo "Run ./scripts/setup-hyperapi-token.sh from the project root first." >&2
  exit 1
fi

BASE_URL="${BASE_URL%/}"
KEYCHAIN_ACCOUNT="${HYPERAPI_KEYCHAIN_ACCOUNT:-$BASE_URL:$USER_ID}"
ACCESS_TOKEN="$(security find-generic-password -a "$KEYCHAIN_ACCOUNT" -s "$KEYCHAIN_SERVICE" -w 2>/dev/null || true)"

if [[ -z "$ACCESS_TOKEN" ]]; then
  echo "Error: access token not found in Keychain." >&2
  echo "Run ./scripts/setup-hyperapi-token.sh from the project root first." >&2
  exit 1
fi

umask 077
tmp="$(mktemp)"
{
  printf '# Generated by init-env-from-keychain.sh. Do not commit this file.\n\n'
  printf 'HYPERAPI_BASE_URL=%s\n' "$BASE_URL"
  printf 'HYPERAPI_USER_ID=%s\n' "$USER_ID"
  printf 'HYPERAPI_ACCESS_TOKEN=%s\n' "$ACCESS_TOKEN"
  printf 'HYPERAPI_INCLUDE_ALL_SUBSCRIPTIONS=%s\n' "${HYPERAPI_INCLUDE_ALL_SUBSCRIPTIONS:-true}"
  printf 'HYPERAPI_HIDE_EXHAUSTED=%s\n' "${HYPERAPI_HIDE_EXHAUSTED:-false}"
  printf 'HYPERAPI_TIMEZONE=%s\n' "${HYPERAPI_TIMEZONE:-Asia/Shanghai}"
} > "$tmp"
mv "$tmp" "$OUT_ENV_FILE"

echo "Wrote $OUT_ENV_FILE for OpenClaw balance checks."
echo "User ID: <redacted>"
echo "Token: <redacted>"
